package domain

// TaskFields holds all scoreable fields of a task card.
type TaskFields struct {
	ContextAndNeed     string `json:"context_and_need"`
	DataAndMaterials   string `json:"data_and_materials"`
	ExpectedResult     string `json:"expected_result"`
	SuccessCriteria    string `json:"success_criteria"`
	Constraints        string `json:"constraints"`
	TargetUsers        string `json:"target_users"`
	ContactAndFeedback string `json:"contact_and_feedback"`
}

// Task is a published business challenge.
type Task struct {
	ID             string     `json:"id"`
	Title          string     `json:"title"`
	Topic          string     `json:"topic"`
	Fields         TaskFields `json:"fields"`
	Rating         int        `json:"rating"`
	ReadinessLevel string     `json:"readiness_level"`
	Status         string     `json:"status"`
}

// Team is a student team that can submit proposals.
type Team struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Skills []string `json:"skills"`
	Focus  string   `json:"focus"`
}

// Proposal is a team's response to a task.
type Proposal struct {
	ID           string `json:"id"`
	TaskID       string `json:"task_id"`
	TeamID       string `json:"team_id"`
	TeamName     string `json:"team_name"`
	SolutionIdea string `json:"solution_idea"`
	Plan         string `json:"plan"`
	Status       string `json:"status"`
}

// DraftQuestion is a clarifying question generated by the AI.
type DraftQuestion struct {
	Field string `json:"field"`
	Text  string `json:"text"`
}

// AnalysisResult is the output of the AI draft analysis.
type AnalysisResult struct {
	Topic     string          `json:"topic"`
	Questions []DraftQuestion `json:"questions"`
}
